/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as GroupRouteImport } from './routes/group'
import { Route as IeltsRouteImport } from './routes/ielts'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StoryRouteImport } from './routes/story'
import { Route as WriteRouteImport } from './routes/write'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as EnterTokenRouteImport } from './routes/enter.$token'
import { Route as IeltsListeningRouteImport } from './routes/ielts_.listening'
import { Route as IeltsMockRouteImport } from './routes/ielts_.mock'
import { Route as IeltsReadingRouteImport } from './routes/ielts_.reading'
import { Route as IeltsSpeakingRouteImport } from './routes/ielts_.speaking'
import { Route as IeltsWritingRouteImport } from './routes/ielts_.writing'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as TeacherGroupIdRouteImport } from './routes/teacher/$groupId'
import { Route as TeacherStudentStudentIdRouteImport } from './routes/teacher/student.$studentId'
import { Route as ApiPublicTelegramCronRouteImport } from './routes/api/public/telegram/cron'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsRoute = IeltsRouteImport.update({
  id: '/ielts',
  path: '/ielts',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterTokenRoute = EnterTokenRouteImport.update({
  id: '/enter/$token',
  path: '/enter/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsListeningRoute = IeltsListeningRouteImport.update({
  id: '/ielts_/listening',
  path: '/ielts/listening',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsMockRoute = IeltsMockRouteImport.update({
  id: '/ielts_/mock',
  path: '/ielts/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsReadingRoute = IeltsReadingRouteImport.update({
  id: '/ielts_/reading',
  path: '/ielts/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsSpeakingRoute = IeltsSpeakingRouteImport.update({
  id: '/ielts_/speaking',
  path: '/ielts/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsWritingRoute = IeltsWritingRouteImport.update({
  id: '/ielts_/writing',
  path: '/ielts/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherGroupIdRoute = TeacherGroupIdRouteImport.update({
  id: '/teacher/$groupId',
  path: '/teacher/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentStudentIdRoute = TeacherStudentStudentIdRouteImport.update({
  id: '/teacher/student/$studentId',
  path: '/teacher/student/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramCronRoute = ApiPublicTelegramCronRouteImport.update({
  id: '/api/public/telegram/cron',
  path: '/api/public/telegram/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/duel': typeof DuelRoute
  '/group': typeof GroupRoute
  '/ielts': typeof IeltsRoute
  '/league': typeof LeagueRoute
  '/review': typeof ReviewRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/write': typeof WriteRoute
  '/admin/setup': typeof AdminSetupRoute
  '/enter/$token': typeof EnterTokenRoute
  '/ielts/listening': typeof IeltsListeningRoute
  '/ielts/mock': typeof IeltsMockRoute
  '/ielts/reading': typeof IeltsReadingRoute
  '/ielts/speaking': typeof IeltsSpeakingRoute
  '/ielts/writing': typeof IeltsWritingRoute
  '/teacher/$groupId': typeof TeacherGroupIdRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/student/$studentId': typeof TeacherStudentStudentIdRoute
  '/api/public/telegram/cron': typeof ApiPublicTelegramCronRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/duel': typeof DuelRoute
  '/group': typeof GroupRoute
  '/ielts': typeof IeltsRoute
  '/league': typeof LeagueRoute
  '/review': typeof ReviewRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/write': typeof WriteRoute
  '/admin/setup': typeof AdminSetupRoute
  '/enter/$token': typeof EnterTokenRoute
  '/ielts/listening': typeof IeltsListeningRoute
  '/ielts/mock': typeof IeltsMockRoute
  '/ielts/reading': typeof IeltsReadingRoute
  '/ielts/speaking': typeof IeltsSpeakingRoute
  '/ielts/writing': typeof IeltsWritingRoute
  '/teacher/$groupId': typeof TeacherGroupIdRoute
  '/admin': typeof AdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/student/$studentId': typeof TeacherStudentStudentIdRoute
  '/api/public/telegram/cron': typeof ApiPublicTelegramCronRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/duel': typeof DuelRoute
  '/group': typeof GroupRoute
  '/ielts': typeof IeltsRoute
  '/league': typeof LeagueRoute
  '/review': typeof ReviewRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/write': typeof WriteRoute
  '/admin/setup': typeof AdminSetupRoute
  '/enter/$token': typeof EnterTokenRoute
  '/ielts_/listening': typeof IeltsListeningRoute
  '/ielts_/mock': typeof IeltsMockRoute
  '/ielts_/reading': typeof IeltsReadingRoute
  '/ielts_/speaking': typeof IeltsSpeakingRoute
  '/ielts_/writing': typeof IeltsWritingRoute
  '/teacher/$groupId': typeof TeacherGroupIdRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/student/$studentId': typeof TeacherStudentStudentIdRoute
  '/api/public/telegram/cron': typeof ApiPublicTelegramCronRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/duel'
    | '/group'
    | '/ielts'
    | '/league'
    | '/review'
    | '/shop'
    | '/story'
    | '/write'
    | '/admin/setup'
    | '/enter/$token'
    | '/ielts/listening'
    | '/ielts/mock'
    | '/ielts/reading'
    | '/ielts/speaking'
    | '/ielts/writing'
    | '/teacher/$groupId'
    | '/admin/'
    | '/teacher/'
    | '/teacher/student/$studentId'
    | '/api/public/telegram/cron'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/duel'
    | '/group'
    | '/ielts'
    | '/league'
    | '/review'
    | '/shop'
    | '/story'
    | '/write'
    | '/admin/setup'
    | '/enter/$token'
    | '/ielts/listening'
    | '/ielts/mock'
    | '/ielts/reading'
    | '/ielts/speaking'
    | '/ielts/writing'
    | '/teacher/$groupId'
    | '/admin'
    | '/teacher'
    | '/teacher/student/$studentId'
    | '/api/public/telegram/cron'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/duel'
    | '/group'
    | '/ielts'
    | '/league'
    | '/review'
    | '/shop'
    | '/story'
    | '/write'
    | '/admin/setup'
    | '/enter/$token'
    | '/ielts_/listening'
    | '/ielts_/mock'
    | '/ielts_/reading'
    | '/ielts_/speaking'
    | '/ielts_/writing'
    | '/teacher/$groupId'
    | '/admin/'
    | '/teacher/'
    | '/teacher/student/$studentId'
    | '/api/public/telegram/cron'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DuelRoute: typeof DuelRoute
  GroupRoute: typeof GroupRoute
  IeltsRoute: typeof IeltsRoute
  LeagueRoute: typeof LeagueRoute
  ReviewRoute: typeof ReviewRoute
  ShopRoute: typeof ShopRoute
  StoryRoute: typeof StoryRoute
  WriteRoute: typeof WriteRoute
  AdminSetupRoute: typeof AdminSetupRoute
  EnterTokenRoute: typeof EnterTokenRoute
  IeltsListeningRoute: typeof IeltsListeningRoute
  IeltsMockRoute: typeof IeltsMockRoute
  IeltsReadingRoute: typeof IeltsReadingRoute
  IeltsSpeakingRoute: typeof IeltsSpeakingRoute
  IeltsWritingRoute: typeof IeltsWritingRoute
  TeacherGroupIdRoute: typeof TeacherGroupIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherStudentStudentIdRoute: typeof TeacherStudentStudentIdRoute
  ApiPublicTelegramCronRoute: typeof ApiPublicTelegramCronRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts': {
      id: '/ielts'
      path: '/ielts'
      fullPath: '/ielts'
      preLoaderRoute: typeof IeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter/$token': {
      id: '/enter/$token'
      path: '/enter/$token'
      fullPath: '/enter/$token'
      preLoaderRoute: typeof EnterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts_/listening': {
      id: '/ielts_/listening'
      path: '/ielts/listening'
      fullPath: '/ielts/listening'
      preLoaderRoute: typeof IeltsListeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts_/mock': {
      id: '/ielts_/mock'
      path: '/ielts/mock'
      fullPath: '/ielts/mock'
      preLoaderRoute: typeof IeltsMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts_/reading': {
      id: '/ielts_/reading'
      path: '/ielts/reading'
      fullPath: '/ielts/reading'
      preLoaderRoute: typeof IeltsReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts_/speaking': {
      id: '/ielts_/speaking'
      path: '/ielts/speaking'
      fullPath: '/ielts/speaking'
      preLoaderRoute: typeof IeltsSpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts_/writing': {
      id: '/ielts_/writing'
      path: '/ielts/writing'
      fullPath: '/ielts/writing'
      preLoaderRoute: typeof IeltsWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$groupId': {
      id: '/teacher/$groupId'
      path: '/teacher/$groupId'
      fullPath: '/teacher/$groupId'
      preLoaderRoute: typeof TeacherGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/student/$studentId': {
      id: '/teacher/student/$studentId'
      path: '/teacher/student/$studentId'
      fullPath: '/teacher/student/$studentId'
      preLoaderRoute: typeof TeacherStudentStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/cron': {
      id: '/api/public/telegram/cron'
      path: '/api/public/telegram/cron'
      fullPath: '/api/public/telegram/cron'
      preLoaderRoute: typeof ApiPublicTelegramCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DuelRoute: DuelRoute,
  GroupRoute: GroupRoute,
  IeltsRoute: IeltsRoute,
  LeagueRoute: LeagueRoute,
  ReviewRoute: ReviewRoute,
  ShopRoute: ShopRoute,
  StoryRoute: StoryRoute,
  WriteRoute: WriteRoute,
  AdminSetupRoute: AdminSetupRoute,
  EnterTokenRoute: EnterTokenRoute,
  IeltsListeningRoute: IeltsListeningRoute,
  IeltsMockRoute: IeltsMockRoute,
  IeltsReadingRoute: IeltsReadingRoute,
  IeltsSpeakingRoute: IeltsSpeakingRoute,
  IeltsWritingRoute: IeltsWritingRoute,
  TeacherGroupIdRoute: TeacherGroupIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherStudentStudentIdRoute: TeacherStudentStudentIdRoute,
  ApiPublicTelegramCronRoute: ApiPublicTelegramCronRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
